apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-cloud-k8s-provider
  namespace: bjrdc-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-cloud-k8s-provider
  template:
    metadata:
      labels:
        app: spring-cloud-k8s-provider
    spec:
      serviceAccountName: default
      hostAliases:
      - ip: 172.16.15.37
        hostnames:
        - bjrdc37
      containers:
      - name: provider-server
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8093