eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    statusPageUrlPath: ${server.servlet.contextPath}/actuator/health
    healthCheckUrlPath: ${server.servlet.contextPath}/actuator/health
