management:
  server:
    port: 9082
  metrics:
    web:
      server:
        auto-time-requests: false
server:
  port: 8082
spring:
  application:
    name: zipkin
eureka:
  instance:
    appname: zipkin