apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-cloud-config
  namespace: bjrdc-dev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-cloud-config
    spec:
      hostAliases:
      - ip: "172.16.15.7"
        hostnames:
        - "bjrdc7"    
      containers:
      - imagePullPolicy: Always
