management:
  server:
    port: 9097
server:
  port: 8097
service:
  servlet:
    contextPath:
      consumer: sc-k8s-consumer
      provider: sc-k8s-provider
spring:
  cloud:
    gateway:
      routes:
      - id: provider
        uri: http://spring-cloud-k8s-provider.bjrdc-dev.svc.cluster.local:8093
        predicates:
        - Path=/provider/**
        filters:
        - StripPrefix=1
        - RewritePath=/(?<segment>.*), /${service.servlet.contextPath.provider}/$\{segment}
      - id: consumer
        uri: http://spring-cloud-k8s-consumer.bjrdc-dev.svc.cluster.local:8096
        predicates:
        - Path=/consumer/**
        filters:
        - StripPrefix=1
        - RewritePath=/(?<segment>.*), /${service.servlet.contextPath.consumer}/$\{segment}