apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sc-gateway-ingress
  namespace: bjrdc-dev
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "20M"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: ingress.bjrdc17
    http:
      paths:
      - path: /sc-gateway/(.*)
        backend:
          serviceName: spring-cloud-k8s-gateway
          servicePort: 8097