server:
  port: 8400
spring:
  profiles:
    active: csdn
zuul:
  routes:
    consumer: /consumer/**
    provider: /provider/**
#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 80000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 80000

