server:
  port: 8083
  servlet:
    contextPath: /sc-provider
eureka:
  instance:
    appname: provider
spring:
  application:
    name: provider
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config
      fail-fast: true
      username: root
      password: i
  sleuth:
    sampler:
      percentage: 1.0