kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ceph-mysql-cluster-pvc-01
  namespace: bjrdc-dev
spec:
  selector:
    matchLabels:
      pv: ceph-mysql-cluster-pv-01
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

