management:
  server:
    port: 9096
server:
  port: 8098
spring:
  application:
    name: spring-cloud-k8s-configmap
  sleuth:
    sampler:
      percentage: 1.0
backend:
  ribbon:
    eureka:
      enabled: false
    client:
      enabled: true
    ServerListRefreshInterval: 5000
 