apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-cloud-config
  namespace: bjrdc-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-cloud-config
  template:
    metadata:
      labels:
        app: spring-cloud-config
    spec:
      containers:
      - name: config-server
        image: bjrdc206.reg/bjrdc-dev/spring-cloud-config:0.0.1-SNAPSHOT
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8081
