management:
  server:
    port: 9086
server:
  port: 8086
  servlet:
    contextPath: /sc-consumer
eureka:
  instance:
    appname: consumer
spring:
  application:
    name: consumer
  sleuth:
    sampler:
      percentage: 1.0