eureka:
  client:
    service-url:
      defaultZone: http://root:i@spring-cloud-eureka.bjrdc-dev.svc.cluster.local:8080/eureka/
  
spring:
  zipkin:
    base-url: http://spring-cloud-zipkin.bjrdc-dev.svc.cluster.local:8082
 