server:
  port: 8086
  servlet:
    contextPath: /sc-consumer
eureka:
  instance:
    appname: consumer
spring:
  application:
    name: consumer
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config
      fail-fast: true
      username: root
      password: i
  sleuth:
    sampler:
      percentage: 1.0