server:
  port: 8086
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    appname: consumer

spring:
  sleuth:
    sampler:
      percentage: 1.0
  application:
    name: consumer
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config
      fail-fast: true
      username: root
      password: i
management:
  endpoints:
    web:
      exposure:
        include: '*'