server:
  port: 8080
eureka:
  datacenter: trmap
  server:
      # 关闭自我保护
      enable-self-preservation: false
      # 清理服务器
      eviction-interval-timer-in-ms: 5000
  client:
    healthcheck:
      enabled: true
    register-with-eureka: false
    fetch-registry: false
spring:
  security:
    basic:
      enabled: true
    user:
      name: root
      password: i