apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
      - name: eureka-server
        image: codingsoldier/eureka-server:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 10001
