apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-cloud-provider
  namespace: bjrdc-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-cloud-provider
  template:
    metadata:
      labels:
        app: spring-cloud-provider
    spec:
      hostAliases:
      - ip: 172.16.15.37
        hostnames:
        - bjrdc37
      containers:
      - name: provider-server
        image: bjrdc206.reg/bjrdc-dev/spring-cloud-provider:0.0.1-SNAPSHOT
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8083