management:
  server:
    port: 9081
server:
  port: 8081
  servlet:
    contextPath: /sc-config
spring:
  security:
    basic:
      enabled: true
    user:
      name: root
      password: i
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: http://bjrdc7:8090/moa/spring-cloud-configdata.git
          searchPaths: config-properties
          username: bjrdc-public3
          password: zgjx@321
eureka:
  instance:
    appname: config
    metadataMap:
      configPath: ${server.servlet.contextPath}
      
