server:
  port: 8081
spring:
  security:
    basic:
      enabled: true
    user:
      name: root
      password: i
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/icesx/ISpring-cloud
          searchPaths: spring-cloud-common/spring-cloud-config/config
          username: 
          password: 
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    appname: config
    
logging:
  level:
    root: INFO        
    org:
      springframework: 
        security: INFO
        web: INFO    
      hibernate: INFO        
      apache:
        commons:
          dbcp2: INFO 