apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-on-ceph-01
  namespace: bjrdc-dev
spec:
  selector:
    matchLabels:
      app: mysql-on-ceph-01
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-on-ceph-01
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: xjgz@123
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim: 
          claimName: ceph-mysql-pvc-01
