apiVersion: v1
kind: Service
metadata:
  name: mysql-ceph-service-01
  namespace: bjrdc-dev
  labels:
    app: mysql-ceph-service-01
spec:
  selector:
      app: mysql-on-ceph-01
  ports:
  - protocol : TCP
    port: 3306
    targetPort: 3306
