management:
  server:
    port: 9084
server:
  port: 8084
  servlet:
    contextPath: /sc-zuul
eureka:
  instance:
    appname: zuul
spring:
  sleuth:
    sampler:
      percentage: 1.0
  application:
    name: zuul